### ISSUE TITLE
kiez.life ist offline

### ISSUE THREAD

**Issue by almereyda** [paszin/kiez-kneipen#1]
> Wo krieg' ich denn jetzt ein Bier her?

könnte eine Frage einer enttäuschten Nutzerin sein.

Daher sei stellvertretend in ihrem Namen hier ein Hinweis darauf hinterlassen, dass die Seite, welche im CNAME erwähnt wird, keine Seite ausliefert. D.h. entweder CNAME entfernen und über GitHub hosten, oder die Seite zu reparieren könnte helfen.

:beers:

**Comment by paszin** [comment]
Hi @almereyda,

sehr aufmerksam! Ich hoffe, dass alle Nutzer der Seite sich mittlerweile ein bisschen im Kiez auskennen  und so in den letzten drei Tagen über die Runden gekommen sind ;)

Die CNAME hab ich entfernt, der schnellste Weg zur Seite ist jetzt über http://bit.ly/kiezlife

Cheers :beers:

**Comment by almereyda** [comment]
Danke für die prompte Reaktion.

Ich fand's nur witzig, da aus https://commons.blog/2013/12/13/mapping-the-alternatives-kiezmap/ entstanden jetzt Jahre später immernoch @transformap herumgurkt und mich die Domäne an die alte Idee erinnert hatte.
